language: python
python:
  - "2.7"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script:
  - python setup.py install
  - python tests/test_linked_list.py
  - python tests/test_stack.py
  - python tests/test_queue.py
  - python tests/test_hash_table.py
  - python tests/test_make_month.py
  - python tests/test_insertion_sort.py
